### ISSUE TITLE
Allow config to specify work days

### ISSUE THREAD

**Issue by danielma** [danielma/reviewbot#2]
Our office has Fridays off in the summer. Let's make sure we can set the configuration to only send notification on days 1-4

**Comment by shanebonham** [comment]
Bonus points for skipping MCT holidays too.

**Comment by shanebonham** [comment]
It'd be :cool: if it took company holidays into account. Happy Memorial Day.

**Comment by danielma** [comment]
hrm... it should be able to do that through bamboo somehow. I'll create a separate issue
